### PR TITLE
fix: cleanup event-emitter subscriptions in provider hooks

### LINKED ISSUE #390: React hooks leak event-emitter subscriptions, causing CPU growth on Vercel Fluid Compute
`useFlagsmithLoading` and `useFlags` register listeners during render (not in an effect), and their cleanup paths don't remove every listener they registered. 

On long-lived Node processes that share module state between invocations (Vercel, Fluid Compute, serverful SSR), subscriptions accumulate with each mount/unmount, causing a memory leak.
 
`FlagsmithProvider` also calls `flagsmith.init()` during render, which triggers the same accumulation on SSR when options is passed (thee workaround proposed in #389).

### PR DESCRIPTION
**Pull request by Zaimwa9**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have read the [Contributing Guide](/Flagsmith/flagsmith/blob/main/CONTRIBUTING.md).
- [x] I have added information to `docs/` if required so people know about the feature.
- [x] I have filled in the "Changes" section below.
- [x] I have filled in the "How did you test this code" section below.

## Changes

Closes #390 
Hooks were rendering at render time instead than in an effect and the cleanup paths did not remove all registered listeners

- `useFlagsmithLoading` and `useFlags`: subscribe inside useEffect with emitter.on's returned unsubscribe as cleanup. Removes render-time events.on and multi subscription

## How did you test this code?
  | Branch                         | Active listeners after 1000 SSR renders                                                |
  | ------------------------------ | -------------------------------------------------------------------------------------- |
  | `main` (pre-fix)               | **2000** (2 leaked per render: one from `useFlagsmithLoading`, one from `useFlags`)    |
  | `fix/react-subscription-leak`  | **0**                                                                                  |

### CODE REVIEW

File: react.tsx [hunk 1]
```diff
@@ -142,32 +131,27 @@ export function useFlags<F extends string | Record<string, any>, T extends strin
...
-    if (firstRender.current) {
-        firstRender.current = false
-        // @ts-expect-error using internal function, consumers would never call this
-        flagsmith?.log('React - Initialising event listeners')
-    }
 
     useEffect(() => {
+        if (!flagsmith) return
+        setRenderRef(getRenderKey(flagsmith, flags, traits))
+        const unsubscribe = events.on('event', () => {
```
Comment (talissoncosta) [inline react.tsx:142]: Quick question:  was the switch from `events.once` => `events.on` intentional? 

Just want to make sure you're aware it's a behavior change: in the old code each render re-registered a `once` listener (because `useRef`'s arg evaluates every render), so the hook reacted on every emit incidentally. 

With `events.on`, it's a single persistent subscription. Same net behavior for consumers as far as I can tell, but wanted to flag it in case you hadn't spotted it.

**Review by talissoncosta — APPROVED** [review]
Looks good, just one question. Not blocking

File: react.tsx (hunk 1 above)
Comment (Zaimwa9) [reply react.tsx:142]: Yes that was intentional. That's part of the leak, the `once` was recreating a subscription on each render but the useRef was only keeping the first listener. In terms of behavior the 2 implementations should be strictly the same for the end-user and this `on` is properly cleaned up now on unmount
